### ISSUE TITLE
Implementation of baselines

### ISSUE THREAD

**Issue by MoeinSorkhei** [zhangyikaii/Model-Spider#1]
Hello, thanks for the nice work.
Is there implementation of baseline methods, such as LFC, in your code?
The `mptms` module seems to be imported in `feature_extractor` in the code but I could not find the module itself.

**Comment by zhangyikaii** [comment]
Hi,
Thank you very much for your attention. I have already updated the baseline code. I've been a little busy lately, but will provide more detailed instructions in the near future. Your support is greatly appreciated. Please stay tuned!
